### Obter todas as transações
GET http://localhost:3000/api/transactions

### Criar transação
POST http://localhost:3000/api/transactions
Content-Type: application/json

{
    "type": "expense",
    "amount": 12,
    "category": "Health",
    "description": "comprar medicina",
    "date": "26-02-2026"
}

### Filtrar transações &category=other&month=11&year=2024
GET http://localhost:3000/api/transactions?category=other

### Obter transação por ID
GET http://localhost:3000/api/transactions/c6d2a0bb-d9c4-4b34-9d6b-4da3b8cd14e1

### Atualizar uma transação
PATCH http://localhost:3000/api/transactions/a1f02605-aaaa-4a11-b111-000000000132
Content-Type: application/json

{
    "amount" : 251
}

### Excluir uma transação
DELETE http://localhost:3000/api/transactions/c6d2a0bb-d9c4-4b34-9d6b-4da3b8cd14e1

### Ver o saldo
GET http://localhost:3000/api/stats/balance

### Filtrar saldo
GET http://localhost:3000/api/stats/balance?year=2024&month=12

### Gastos por categoria
GET http://localhost:3000/api/stats/by-category

### Filtrar gastos por categoria por mês e ano
GET http://localhost:3000/api/stats/by-category?month=1&year=2026

### Resumo mensal
GET http://localhost:3000/api/stats/monthly

### Filtrar resumo mensal por mês e ano
GET http://localhost:3000/api/stats/monthly?month=12&year=2025

### Principais categorias
GET http://localhost:3000/api/stats/top-categories

### Filtrar principais categorias
GET http://localhost:3000/api/stats/top-categories?month=12&year=2024

### Ver categorias
GET http://localhost:3000/api/categories

### Ver categoria por ID
GET http://localhost:3000/api/categories/1

### Criar categoria
POST http://localhost:3000/api/categories
Content-Type: application/json

{
    "name": "regalos"
}

### Atualizar categoria
PUT http://localhost:3000/api/categories/1
Content-Type: application/json

{
    "name": "Comida"
}

### Excluir uma categoria
DELETE http://localhost:3000/api/categories/1