### Obtener todas las transaction
GET http://localhost:3000/api/transactions

### Crear transaction
POST http://localhost:3000/api/transactions
Content-Type: application/json

{
    "type": "expense",
    "amount": 12,
    "category": "Health",
    "description": "comprar medicina"
}

### Filtrar transaction &category=other&month=11&year=2024
GET http://localhost:3000/api/transactions?category=other

### Obtener transaction por id
GET http://localhost:3000/api/transactions/c6d2a0bb-d9c4-4b34-9d6b-4da3b8cd14e1

### Actualizar una transaction
PATCH http://localhost:3000/api/transactions/a1f02605-aaaa-4a11-b111-000000000132
Content-Type: application/json

{
    "amount" : 251
}

### Eliminar una transaction
DELETE http://localhost:3000/api/transactions/c6d2a0bb-d9c4-4b34-9d6b-4da3b8cd14e1

### Ver el balance
GET http://localhost:3000/api/stats/balance

### Filtrar el balance
GET http://localhost:3000/api/stats/balance?year=2024&month=12

### Gastos por categoria
GET http://localhost:3000/api/stats/by-category

### Filtrar Gastos por categoria por mes y año
GET http://localhost:3000/api/stats/by-category?month=1&year=2026

### Resumen mensual
GET http://localhost:3000/api/stats/monthly

### Filtrar resumen mensual por mes y año
GET http://localhost:3000/api/stats/monthly?month=12&year=2025

### Top Categories
GET http://localhost:3000/api/stats/top-categories

###Top categorias por filtro 
GET http://localhost:3000/api/stats/top-categories?month=12&year=2024

### Ver categorias
GET http://localhost:3000/api/categories

### Ver categoria por id
GET http://localhost:3000/api/categories/1

### Crear categoria
POST http://localhost:3000/api/categories
Content-Type: application/json

{
    "name": "home"
}

### Actualizar categoria
PUT http://localhost:3000/api/categories/1
Content-Type: application/json

{
    "name": "Expense home"
}

### Eliminar una categoria
DELETE http://localhost:3000/api/categories/1